export const TOGGLE_SWITCHER = 'TOGGLE_SWITCHER';
export const TOGGLE_MODE = 'TOGGLE_MODE';
export const INCREASE_BRIGHTNESS = 'INCREASE_BRIGHTNESS';
export const DECREASE_BRIGHTNESS = 'DECREASE_BRIGHTNESS';