// export const SWITCH_TO_WHITE = 'SWITCH_TO_WHITE';
// export const SWITCH_TO_YELLOW = 'SWITCH_TO_YELLOW';
// export const DISABLE = 'DISABLE';
// export const INCREASE_BRIGHTNESS = 'INCREASE_BRIGHTNESS';
// export const DECREASE_BRIGHTNESS = 'DECREASE_BRIGHTNESS';
export const TOGGLE_SWITCHER = 'TOGGLE_SWITCHER';
export const TOGGLE_MODE = 'TOGGLE_MODE';
export const CHANGE_BRIGHTNESS = 'CHANGE_BRIGHTNESS';